#!/usr/bin/env bash

GENOME_DIR="/home/Public.Resources/Genomes/PanGenome.S130.Final.dir"
DB_DIR="/vol2/ZhangYiFan2023/workspace/centromere/blastdatabase"

for sample_dir in "$GENOME_DIR"/*; do
    sample=$(basename "$sample_dir")
    fasta_file="$sample_dir/genome/${sample}.final.new.fasta"
    out_dir="$DB_DIR/$sample"

    if [[ ! -f "$fasta_file" ]]; then
        echo "⚠️ 跳过 $sample：未找到 $fasta_file"
        continue
    fi

    mkdir -p "$out_dir"
    makeblastdb -in "$fasta_file" \
                -dbtype nucl \
                -out "$out_dir/$sample" \
                -parse_seqids \
                -title "$sample"

done


#!/usr/bin/env bash

QUERY="/vol2/ZhangYiFan2023/workspace/centromere/centromere.fa"
DB_DIR="/vol2/ZhangYiFan2023/workspace/centromere/blastdatabase"

OUT_DIR="/vol2/ZhangYiFan2023/workspace/centromere/blast_result"
mkdir -p "$OUT_DIR"

for sample_dir in "$DB_DIR"/*; do
    sample=$(basename "$sample_dir")
    db_prefix="$sample_dir/$sample"

    if [[ ! -f "${db_prefix}.nhr" ]]; then
        echo "跳过 $sample：未发现 BLAST 数据库 (${db_prefix}.nhr)"
        continue
    fi
    out_file="$OUT_DIR/${sample}.blast.txt"

    # 运行 blastn
    blastn \
        -query "$QUERY" \
        -db "$db_prefix" \
        -out "$out_file" \
        -outfmt 6 \
        -num_threads 40
done

#!/usr/bin/env bash

BLAST_DIR="/vol2/ZhangYiFan2023/workspace/centromere/blast_result"
OUT_DIR="/vol2/ZhangYiFan2023/workspace/centromere/bam.dir"
mkdir -p "$OUT_DIR"

for file in "$BLAST_DIR"/*.txt; do
    sample=$(basename "$file" .blast.txt)
    outfile="$OUT_DIR/${sample}.bed"

    awk '{if ($1=="type_III" && $11 < 1e-5 && $4 > 100) {
            OFS="\t";
            if ($9 < $10) {
                print $2, $9, $10
            } else {
                print $2, $10, $9
            }
        }
    }' "$file" | sort -k1,1 -k2,2n > "$outfile"
done


#!/usr/bin/env bash

indir="/vol2/ZhangYiFan2023/workspace/centromere/bam.dir"
merged_dir="/vol2/ZhangYiFan2023/workspace/centromere/bam.dir/merged"
mkdir -p $merged_dir

output_all="All_Germplasms_Merged_MaxRegion.tsv"
echo -e "Germplasm\tChr\tStart\tEnd\tLength" > $output_all

for bed in $indir/*.bed; do
    germ=$(basename $bed .bed)

    merged_bed="$merged_dir/${germ}.merged.bed"

    bedtools merge -i $bed -d 100000 > $merged_bed

    awk '
        {
            len=$3-$2
            key=$1
            if(len > maxlen[key]) {
                maxlen[key]=len
                line[key]=$0
            }
        }
        END {
            for(k in line) print line[k]
        }
    ' $merged_bed | sort -k1,1 > "$merged_dir/${germ}.max_region.bed"

    awk -v g=$germ '{
        len=$3-$2;
        print g"\t"$1"\t"$2"\t"$3"\t"len
    }' "$merged_dir/${germ}.max_region.bed" >> $output_all

done




